{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.balticamadeus",
    "module": "pope",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "pope-0.4.0.jar",
          "url": "pope-0.4.0.jar",
          "size": 172670,
          "sha512": "9c240a60d3fcf41d60b0d592dc3876de7479524d33e4a3ca8cc41ebad6cf284c3bb3cd334ff33559275fbfd480c128810c38dd939f7cc347d9bc6fba6bbe01e5",
          "sha256": "4192e46b4b81f1f5b717d571d55b0aeba1bcec9015d08d3e30a23fde5c936352",
          "sha1": "de46baf033afa65e1d852c374c156965aa4a6361",
          "md5": "07e0a0d5171895daa0eb404ad0bed56b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250517"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "pope-0.4.0.jar",
          "url": "pope-0.4.0.jar",
          "size": 172670,
          "sha512": "9c240a60d3fcf41d60b0d592dc3876de7479524d33e4a3ca8cc41ebad6cf284c3bb3cd334ff33559275fbfd480c128810c38dd939f7cc347d9bc6fba6bbe01e5",
          "sha256": "4192e46b4b81f1f5b717d571d55b0aeba1bcec9015d08d3e30a23fde5c936352",
          "sha1": "de46baf033afa65e1d852c374c156965aa4a6361",
          "md5": "07e0a0d5171895daa0eb404ad0bed56b"
        }
      ]
    }
  ]
}
