{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.balticamadeus",
    "module": "pope",
    "version": "0.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "pope-0.5.4.jar",
          "url": "pope-0.5.4.jar",
          "size": 180214,
          "sha512": "d9384a66b3f12e0a9b5b3b98db5453d7e020296f79ca37335d1e9eb208f37851552dc3ddddc640bf7c7057cf00339e2f291ca06f0878bd6793146a548a10cb25",
          "sha256": "a60bfbfa2beeead4311b8ca39c441d963f4afcba40cf90b84754db625c704ce6",
          "sha1": "a50ae4e597338ac7fa5631f870e82c9676c140f5",
          "md5": "622e6f7acadc55cc5ea2306afd006ba6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250517"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "pope-0.5.4.jar",
          "url": "pope-0.5.4.jar",
          "size": 180214,
          "sha512": "d9384a66b3f12e0a9b5b3b98db5453d7e020296f79ca37335d1e9eb208f37851552dc3ddddc640bf7c7057cf00339e2f291ca06f0878bd6793146a548a10cb25",
          "sha256": "a60bfbfa2beeead4311b8ca39c441d963f4afcba40cf90b84754db625c704ce6",
          "sha1": "a50ae4e597338ac7fa5631f870e82c9676c140f5",
          "md5": "622e6f7acadc55cc5ea2306afd006ba6"
        }
      ]
    }
  ]
}
