{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.balticamadeus",
    "module": "pope",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "pope-0.1.0.jar",
          "url": "pope-0.1.0.jar",
          "size": 164126,
          "sha512": "8138ef5c3a0a454cc600635e4e630218ab7e6cd7d69af317fc475a486277803a2a9c61f5e60ac6f787315db3b54ee99137dc5b4fd8518d07a99b028ecd357606",
          "sha256": "51aad0f987b5d586639abfc54e5224dd4ea6f97a89e941e18958fad584c7ffab",
          "sha1": "6e484556302a22219f39e0a392277d21e92a91c3",
          "md5": "f8c10be29f25dff0b6b457d2daa8472e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250517"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "pope-0.1.0.jar",
          "url": "pope-0.1.0.jar",
          "size": 164126,
          "sha512": "8138ef5c3a0a454cc600635e4e630218ab7e6cd7d69af317fc475a486277803a2a9c61f5e60ac6f787315db3b54ee99137dc5b4fd8518d07a99b028ecd357606",
          "sha256": "51aad0f987b5d586639abfc54e5224dd4ea6f97a89e941e18958fad584c7ffab",
          "sha1": "6e484556302a22219f39e0a392277d21e92a91c3",
          "md5": "f8c10be29f25dff0b6b457d2daa8472e"
        }
      ]
    }
  ]
}
