{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.balticamadeus",
    "module": "pope",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "pope-0.1.0.jar",
          "url": "pope-0.1.0.jar",
          "size": 164126,
          "sha512": "b79acc8c32eb7a40d00f1cfec52c09dbc409ed3d70d59dfd9305add63fabd754692055c38f1198cfff3c42460b9c8e9332e29d69df9ab8a444c39e3a528ebef8",
          "sha256": "6c3cd9f25d89481c8375b7de3606d5c93d27455732ff13d9f8fbcbb2e069a617",
          "sha1": "0c41fc7cc46e8dca199e98334db8654211420106",
          "md5": "34a511e012974b265b874d88837ba444"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250517"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "pope-0.1.0.jar",
          "url": "pope-0.1.0.jar",
          "size": 164126,
          "sha512": "b79acc8c32eb7a40d00f1cfec52c09dbc409ed3d70d59dfd9305add63fabd754692055c38f1198cfff3c42460b9c8e9332e29d69df9ab8a444c39e3a528ebef8",
          "sha256": "6c3cd9f25d89481c8375b7de3606d5c93d27455732ff13d9f8fbcbb2e069a617",
          "sha1": "0c41fc7cc46e8dca199e98334db8654211420106",
          "md5": "34a511e012974b265b874d88837ba444"
        }
      ]
    }
  ]
}
