{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.balticamadeus",
    "module": "pope",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "pope-0.5.0.jar",
          "url": "pope-0.5.0.jar",
          "size": 178663,
          "sha512": "91b38f41ed8c39bfb323751212522aa5415f0d09e8adaca3635561a99807b0417c8c093022861cbdd989dc7ef2fb7da13ad46f83dfeeeee210575ed6f95c91a6",
          "sha256": "6f53de52d47feec33591b08a344f4c486b8852785de7afc6e313180e6e990e94",
          "sha1": "efb87d10933feea4ab6284158ce73df506d9b484",
          "md5": "013dfd6f2ba69ff619c4c5c32b1e1925"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250517"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "pope-0.5.0.jar",
          "url": "pope-0.5.0.jar",
          "size": 178663,
          "sha512": "91b38f41ed8c39bfb323751212522aa5415f0d09e8adaca3635561a99807b0417c8c093022861cbdd989dc7ef2fb7da13ad46f83dfeeeee210575ed6f95c91a6",
          "sha256": "6f53de52d47feec33591b08a344f4c486b8852785de7afc6e313180e6e990e94",
          "sha1": "efb87d10933feea4ab6284158ce73df506d9b484",
          "md5": "013dfd6f2ba69ff619c4c5c32b1e1925"
        }
      ]
    }
  ]
}
